apiVersion: v1
kind: Service
metadata:
  name: {{ include "aa-suggestions.fullname" . }}
spec:
  selector:
    app: {{ include "aa-suggestions.fullname" . }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      protocol: TCP
  type: {{ .Values.service.type }}