name: Go CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  call-workflow:
    uses: bsrivastava/go-sample-poc2/.github/workflows/learn_github_actions-go.yml

  