name: Go CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
      
jobs:
  call-workflow:
    uses: bsrivastava123/go-sample-poc2/.github/workflows/learn-github-actions-go.yml@main
    with:
      service-name: welcome
      working-directory: 'src'

  