name: Go CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  
jobs:
  call-workflow:
    uses: bsrivastava123/go-sample-library/.github/workflows/buildFrontendPipeline.yml@test2
    with:
      do_require: "false"